version: '3.7'

services:
  bitcoind:
    build:
      dockerfile: Dockerfile
    image: bitcoind:latest
    ## entrypoint: console
    ## command: --prune=1000
    container_name: bitcoind
    env_file: .env.sample
    hostname: bitcoind
    init: true
    networks:
      - net
    ports:
      - 18332:18332
      - 8333:8333
      - 8080:8080
    restart: unless-stopped
    tty: true
    volumes:
      - ./config:/config:ro
      - ./data:/root/.bitcoin:rw
      - ./home:/root/home:rw
  postgres:
    container_name: bitcoin-db
    image: postgres:latest
    build:
      dockerfile: ./Dockerfile-db
    restart: always
    hostname: bitcoin-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - net

networks:
  net:
    name: 'bitcoin'
    ipam:
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1
          aux_addresses:
            bitcoind: 172.25.0.3
            postgres: 172.25.0.2
