FROM postgres:latest

## Define build arguments.
ARG ROOTHOME='/root/home'

## Install dependencies.
RUN apt-get update -y && apt-get install net-tools lsof procps -y

## Add custom profile to bashrc.
RUN PROFILE="$ROOTHOME/.profile" \
  && printf "\n[ -f $PROFILE ] && . $PROFILE\n\n" >> /root/.bashrc

## Uncomment this if you want to wipe all repository lists.
#RUN rm -rf /var/lib/apt/lists/*

## Setup Environment.


